#H2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

#Datasource
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true